---
- name: Add Google Chrome repository key
  apt_key:
    url: https://d1.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome Repository
  apt_repository:
    repo: "deb [arch=amd64] http://d1.google.com/linux/chrome/deb/ stable main"
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present
